server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
         - id: USER-SERVICE
           uri: lb://USER-SERVICE
           predicates:
            - Path=/users/**
         - id: DEPARTMENT-SERVICE
           uri: lb://DEPARTMENT-SERVICE
           predicates: 
            - Path=/departments/**
          
# Eureka Server Configuration          
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost
          
   